# Future option

# WARN_LINE_PCT="30"

# WARN_SIZE_PCT="30"

# 국가코드별 배포 파일 경로

get_target_dir() {

case "$1" in

KOR) echo "/app/deploy/kor/result" ;;

JPN) echo "/app/deploy/jpn/result" ;;

CAM) echo "/app/deploy/cam/result" ;;

*) echo "" ;;

esac

}

# 국가코드별 결과 파일 경로

get_output_file() {

case "$1" in

KOR) echo "/app/message/watch/kor/deploy_check_result.txt" ;;

JPN) echo "/app/message/watch/jpn/deploy_check_result.txt" ;;

CAM) echo "/app/message/watch/cam/deploy_check_result.txt" ;;

*) echo "" ;;

esac

}
